#!/usr/bin/python
import os, sys, getopt, tempfile

def main(argv):
   directory = False
   pathAndPrefix = ''
   try:
      opts, args = getopt.getopt(argv,'d:')
   except getopt.GetoptError:
      print 'mktemp [-d] <path/prefix>'
      sys.exit(2)
   for opt, arg in opts:
      if opt == '-d':
         directory = True
         pathAndPrefix = arg
      else:
         directory = False
   if pathAndPrefix == '':
      pathAndPrefix = sys.argv[1]
   try:
      path, prefix = os.path.split(pathAndPrefix)
      cleanPrefix = prefix.replace('X', '')
      if directory:
         print tempfile.mkdtemp(prefix=cleanPrefix, dir=path)
      else:
         handle, tempPath = tempfile.mkstemp(prefix=cleanPrefix, dir=path)
         print tempPath
      sys.exit()
   except OSError:
      print "invalid path"
      sys.exit(2)

if __name__ == '__main__':
   main(sys.argv[1:])
